### ISSUE TITLE
Rmpz_rootrem() is not documented.

### ISSUE THREAD

**Issue by trizen** [sisyphus/math-gmpz#2]
The function `Rmpz_rootrem()` seems to not be documented in Math::GMPz.

Documentation: [https://gmplib.org/manual/Integer-Roots.html](https://gmplib.org/manual/Integer-Roots.html):

**Comment by sisyphus** [comment]
Thanks for catching that, trizen.
Now fixed in git version of GMPz.pm.

Aiming to release 0.45 around New Year.

Cheers,
Rob

**Comment by trizen** [comment]
Thank you for your time. :)
