### ISSUE TITLE
0.47 build failure with older gmp library

### ISSUE THREAD

**Issue by chargr** [sisyphus/math-gmpz#4]
There appears to be a mismatched parenthesis in 0.47 that is encountered when using an older gmp library.

```
GMPz.xs: In function 'overload_not_equiv':
GMPz.xs:3930: error: too few arguments to function 'my_cmp_z'
GMPz.xs:3930: error: expected ';' before ')' token
GMPz.xs:3930: error: expected statement before ')' token
make: *** [GMPz.o] Error 1
```

```
       if(strEQ(h, "Math::GMPq")) {
#if __GNU_MP_RELEASE < 60099
         ret = my_cmp_z(INT2PTR(mpq_t *, SvIVX(SvRV(b)))), a);
         if(ret != 0) return newSViv(1);
         return newSViv(0);
#else
         ret = mpq_cmp_z(*(INT2PTR(mpq_t *, SvIVX(SvRV(b)))), *a);
         if(ret != 0) return newSViv(1);
         return newSViv(0);
#endif
       }
```

**Comment by sisyphus** [comment]
Thanks for that.
Should now be fixed in github - where it's now fine for me when I build against gmp-5.0.1.
Please check anyway, if you get a chance.
I'll release 0.48 tonight.

Cheers.
Rob

**Comment by chargr** [comment]
Thanks, build worked, but tests are failing.

```
t/_1basic.t ............... Can't load '/home/X/.cpanm/work/1513897040.22360/Math-GMPz-0.48/blib/arch/auto/Math/GMPz/Random/Random.so' for module Math::GMPz::Random: /home/X/.cpanm/work/1513897040.22360/Math-GMPz-0.48/blib/arch/auto/Math/GMPz/Random/Random.so: undefined symbol: gmp_urandomm_ui at /home/Y/perl5/perlbrew/perls/perl-5.20.3/lib/5.20.3/x86_64-linux/DynaLoader.pm line 193.
```

GMP version is 4.1.4

**Comment by sisyphus** [comment]
4.1.4 is 13 years old.
Is it possible for you to update to a more recent version ? Current stable release is 6.1.2.

The Readme states that Math::GMPz requires gmp-4.2.0 or later, and the Makefile.PL spits out a similar message.

I could extend back to support 4.1.4 but there could be a fair bit of work involved.
Not only is gmp_urandomm_ui non-existent in 4.1.4, but so too are gmp_randomb_ui, gmp_randinit_mt and gmp_randinit_set.

Not only would I have to modify the source code to cater for these absences, but I would also have to modify the test script to skip tests involving those functions when gmp version is less than 4.2.

Then I probably have to deal in the same way with some functions in GMPz.xs that did not exist in gmp-4.1.4.

This could all be done - but I would far prefer that you got hold of a gmp version (preferably latest) that was in the "currently supported" range.

If you need help acquiring a later version of gmp, please let me know and I'll try to help.

Cheers,
Rob

**Comment by chargr** [comment]
Yea it's not worth extending support, I can point to newer gmp libraries. Thanks much!
