### ISSUE TITLE
Wrong args supplied to mpz_urandomm function

### ISSUE THREAD

**Issue by trizen** [sisyphus/math-gmpz#5]
Hello!

The latest version seems to have introduced an issue in the `Rmpz_urandomm` function, as illustrated in the following code:

```perl
use 5.010;
use Math::GMPz;

package Number {

    sub new {
        my ($class, $n) = @_;
        bless \$n, $class;
    }

    sub add {
        my ($self, $n) = @_;
        Number->new($$self + $$n);
    }

    my $srand = srand();
    my $state = Math::GMPz::zgmp_randinit_mt();
    Math::GMPz::zgmp_randseed_ui($state, $srand);

    sub irand {
        my ($self) = @_;
        my $x = Math::GMPz->new($$self);
        Math::GMPz::Rmpz_urandomm($x, $state, $x, 1);
        say "x = $x";
        return Number->new($x);

    }
}

my $x = Number->new(42);

say ${$x->irand};           # this works
say ${$x->add($x->irand)};  # this fails
```

Output with perl-5.38.0:

```
x = 41
41
Wrong args supplied to mpz_urandomm function at rand.pl line 23
```

In earlier versions, the above code worked correctly: [see tio.run output](https://tio.run/##bVHLboMwELzzFavUB1BIlVTNBdSot55SVT1XQiY4CQp2kNcohIhvpzZvIvaCYR47Y1Imk21VZchg@7rerH3LHPdUnT3va/9T@JaV0sOFnhh8ZzxkEh6WBXowC0Gwm36FdvgdbHJIKKILRDjwAZ@B36NhwhDhjwgN1qQGKgc3GkXPbsiS45xZE2W10wFsUrNgCUTzJqbagqCkItLq@mm3eA0oqpgGhqqeV5x4GhhiLGIVcNXxZznIWBRksd04ue0qregLxfXumUrPdUyefJJlXM0ZiOMgvzwtgsysuHJuk9yFPok@b0YqpHdYGH@SL4avkqlMiulV5l380tJ32MUaU97fDMU4kgfJV7u6Y@nDMC@gzjHC7SovOCLqv2v3AscoWuKRxglW1T8)

**Comment by sisyphus** [comment]
Yep - I see the same.
Thanks for the demo.

I'm hopeful that I just need to remove the <code>PL_markstack_ptr++;</code> that Rmpz_urandomm (and some other functions do) prior to returning.
But maybe it's not that simple.

I'll get to it later today.

Since the current test suite doesn't expose the problem (on my systems, at least) is it ok to use your demo as the basis for a test that I can add to the test suite ?

Cheers,
Rob

**Comment by sisyphus** [comment]
Heh, the failing Rmpz_urandomm call receives 5 args: the Number object, $x, $state, $x and 1.

I could fix it to ignore that extra first argument (when necessary), but I'd first rather understand (and if possible avoid) the passing of that arg.
Hmmm ... I'm missing something about method calls and/or stack manipulation.

I'd also like to work out how the recent changes to the XS file have enabled that to happen. (Actually, at the moment I'm more baffled as to why it hasn't always happened ;-)

I expect that Rmpz_urandomb and Rmpz_urandomm are similarly afflicted.

Cheers,
Rob

**Comment by trizen** [comment]
> is it ok to use your demo as the basis for a test that I can add to the test suite ?

Sure.

Thanks for taking the time of looking into it. It's a strange issue indeed.

**Comment by sisyphus** [comment]
Here's the patch I'm thinking of:
```
--- GMPz.xs_orig        2023-10-09 20:55:32.950329300 +1100
+++ GMPz.xs     2023-10-09 21:04:03.416582200 +1100
@@ -4929,7 +4929,7 @@
      for(i = 0; i < q; ++i) {
         mpz_urandomb(*(INT2PTR(mpz_t *, SvIVX(SvRV(ST(i))))), *(INT2PTR(gmp_randstate_t *, SvIVX(SvRV(ST(thingies - 3))))), (mp_bitcnt_t)SvUV(ST(thingies - 2)));
         }
-     PL_markstack_ptr++;
+     /*PL_markstack_ptr++;*/ /*instead do this in the XS section*/
      XSRETURN(0);
 }

@@ -4945,7 +4945,7 @@
      for(i = 0; i < q; ++i) {
         mpz_urandomm(*(INT2PTR(mpz_t *, SvIVX(SvRV(ST(i))))), *(INT2PTR(gmp_randstate_t *, SvIVX(SvRV(ST(thingies - 3))))), *(INT2PTR(mpz_t *, SvIVX(SvRV(ST(thingies - 2))))));
         }
-     PL_markstack_ptr++;
+     /*PL_markstack_ptr++;*/ /*instead do this in the XS section */
      XSRETURN(0);
 }

@@ -4961,7 +4961,7 @@
      for(i = 0; i < q; ++i) {
         mpz_rrandomb(*(INT2PTR(mpz_t *, SvIVX(SvRV(ST(i))))), *(INT2PTR(gmp_randstate_t *, SvIVX(SvRV(ST(thingies - 3))))), (mp_bitcnt_t)SvUV(ST(thingies - 2)));
         }
-     PL_markstack_ptr++;
+     /*PL_markstack_ptr++;*/ /*instead do this in the XS section*/
      XSRETURN(0);
 }

@@ -7534,6 +7534,7 @@
 Rmpz_urandomb (p, ...)
        SV *    p
         CODE:
+        PL_markstack_ptr++;
         Rmpz_urandomb(aTHX_ p);
         XSRETURN_EMPTY; /* return empty stack */

@@ -7541,6 +7542,7 @@
 Rmpz_urandomm (x, ...)
        SV *    x
         CODE:
+        PL_markstack_ptr++;
         Rmpz_urandomm(aTHX_ x);
         XSRETURN_EMPTY; /* return empty stack */

@@ -7548,6 +7550,7 @@
 Rmpz_rrandomb (x, ...)
        SV *    x
         CODE:
+        PL_markstack_ptr++;
         Rmpz_rrandomb(aTHX_ x);
         XSRETURN_EMPTY; /* return empty stack */
```

Not yet sure if that's what I'll implement, (I ought to do some more thinking.)

Cheers,
Rob
